import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#cbe9d9",
        "on-tertiary": "#ffffff",
        tertiary: "#082319",
        "primary-fixed-dim": "#eabcb8",
        "inverse-primary": "#eabcb8",
        "on-secondary-container": "#656464",
        "surface-container-lowest": "#ffffff",
        secondary: "#5f5e5e",
        "surface-container": "#f5eceb",
        "on-surface-variant": "#504443",
        "inverse-surface": "#342f2f",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f8efee",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#2e1413",
        "primary-container": "#4a2c2a",
        "surface-dim": "#e1d8d7",
        primary: "#321716",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#5f3e3c",
        "on-tertiary-fixed-variant": "#324c40",
        "secondary-fixed": "#e5e2e1",
        "surface-tint": "#795553",
        "error-container": "#ffdad6",
        "tertiary-container": "#1f392e",
        "surface-container-low": "#fbf2f0",
        "surface-variant": "#e9e1df",
        "surface-container-highest": "#e9e1df",
        "on-secondary-fixed-variant": "#474646",
        "on-background": "#1e1b1a",
        "primary-fixed": "#ffdad7",
        "secondary-fixed-dim": "#c8c6c5",
        surface: "#fff8f7",
        "surface-container-high": "#efe6e5",
        "on-surface": "#1e1b1a",
        "on-primary-container": "#bd928f",
        outline: "#827472",
        error: "#ba1a1a",
        "outline-variant": "#d4c3c1",
        "on-tertiary-fixed": "#052016",
        "surface-bright": "#fff8f7",
        "secondary-container": "#e5e2e1",
        background: "#fff8f7",
        "tertiary-fixed-dim": "#b0cdbe",
        "on-tertiary-container": "#86a394",
        "on-error-container": "#93000a",
        "brand-accent": "#D4A373",
        "brand-green": "#2E7D32",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-lg": "32px",
        "stack-md": "16px",
        "container-max": "1200px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-padding": "80px",
        gutter: "24px",
        "stack-sm": "8px",
        unit: "8px",
      },
      fontFamily: {
        "display-lg": ["var(--font-playfair)", "serif"],
        "headline-md": ["var(--font-playfair)", "serif"],
        "title-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["3.5rem", { lineHeight: "1.1" }],
        "display-lg-mobile": ["2.25rem", { lineHeight: "1.15" }],
        "headline-md": ["2rem", { lineHeight: "1.2" }],
        "body-lg": ["1.125rem", { lineHeight: "1.6" }],
        "title-lg": ["1.25rem", { lineHeight: "1.4" }],
        "label-md": ["0.875rem", { lineHeight: "1.4" }],
        "label-sm": ["0.75rem", { lineHeight: "1.4" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
